### PR TITLE
a few updates

### PR DESCRIPTION
**Pull request by tibbben**
Hi there Jochen,

I like your simple tool, works very well. I just made a few changes - perhaps you will merge them in.

- included 'Transparent' and 'BandCount' as parameters for the WMS request
- updated the yaml reader to include FullLoader (avoids python warning)
- made the WMS request respect the Format in the config.yml
- made the calls to gdal to respect the Format in the config.yml
- updated the readme to reflect these changes

note that for a non-transparent request, simply set Transparent to FALSE and BandCount to 3 (or less). To get transparencies set Transparent to TRUE and BandCount to 4 (if the server supports transparencies).

thanks for the tool :)
tim

### CODE REVIEW

**Comment by jochenklar** [comment]
Cool, thanks a lot!

**Comment by tibbben** [comment]
Great!
Could you perhaps make a new release so people can get the updated version from pypi? Would make it easy for some colleagues to simply use the file.
best
tim

**Comment by jochenklar** [comment]
Ok, done: https://pypi.org/project/wms-downloader/

**Comment by tibbben** [comment]
awesome, thanks!

**Pull request merged**
